version: 1.10.{build}
image: Visual Studio 2022
before_build:
  - nuget restore -Verbosity quiet
configuration:
  - Debug
  - Release
platform:
  - Any CPU
  - x86
  - x64
  - ARM64
build:
  project: eduEx.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: bin\$(configuration)\$(platform)
